#!/usr/bin/env bash
set -Eeou pipefail

NIXARGS=(--extra-experimental-features 'nix-command flakes')
# First argument is the nix script we want to run, the remaining arguments are passed to the script
COMMAND="$1"
shift

case $COMMAND in
shell)
    exec nix "${NIXARGS[@]}" develop
    ;;

*)
    # All arguments after `--` are passed to the script you are executing
    exec nix "${NIXARGS[@]}" run ".#${COMMAND}" -- "$@"
    ;;
esac
